import './globals.css'
import { Raleway, Roboto } from 'next/font/google'

const raleway = Raleway({
  weight: '700',
  subsets: ['latin']
})

const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* <NavApp></NavApp> */}
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
